# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/linuxdev/Desktop/Projects/Freelance/33027826_WordBlast

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/linuxdev/Desktop/Projects/Freelance/33027826_WordBlast/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/linuxdev/Desktop/Projects/Freelance/33027826_WordBlast/build/CMakeFiles /home/linuxdev/Desktop/Projects/Freelance/33027826_WordBlast/build/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/linuxdev/Desktop/Projects/Freelance/33027826_WordBlast/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named WordList

# Build rule for target.
WordList: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 WordList
.PHONY : WordList

# fast build rule for target.
WordList/fast:
	$(MAKE) -f CMakeFiles/WordList.dir/build.make CMakeFiles/WordList.dir/build
.PHONY : WordList/fast

#=============================================================================
# Target rules for targets named wordList.h

# Build rule for target.
wordList.h: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wordList.h
.PHONY : wordList.h

# fast build rule for target.
wordList.h/fast:
	$(MAKE) -f CMakeFiles/wordList.h.dir/build.make CMakeFiles/wordList.h.dir/build
.PHONY : wordList.h/fast

nicholas_wynne_hw4_main.o: nicholas_wynne_hw4_main.c.o

.PHONY : nicholas_wynne_hw4_main.o

# target to build an object file
nicholas_wynne_hw4_main.c.o:
	$(MAKE) -f CMakeFiles/WordList.dir/build.make CMakeFiles/WordList.dir/nicholas_wynne_hw4_main.c.o
.PHONY : nicholas_wynne_hw4_main.c.o

nicholas_wynne_hw4_main.i: nicholas_wynne_hw4_main.c.i

.PHONY : nicholas_wynne_hw4_main.i

# target to preprocess a source file
nicholas_wynne_hw4_main.c.i:
	$(MAKE) -f CMakeFiles/WordList.dir/build.make CMakeFiles/WordList.dir/nicholas_wynne_hw4_main.c.i
.PHONY : nicholas_wynne_hw4_main.c.i

nicholas_wynne_hw4_main.s: nicholas_wynne_hw4_main.c.s

.PHONY : nicholas_wynne_hw4_main.s

# target to generate assembly for a file
nicholas_wynne_hw4_main.c.s:
	$(MAKE) -f CMakeFiles/WordList.dir/build.make CMakeFiles/WordList.dir/nicholas_wynne_hw4_main.c.s
.PHONY : nicholas_wynne_hw4_main.c.s

wordList.o: wordList.c.o

.PHONY : wordList.o

# target to build an object file
wordList.c.o:
	$(MAKE) -f CMakeFiles/WordList.dir/build.make CMakeFiles/WordList.dir/wordList.c.o
	$(MAKE) -f CMakeFiles/wordList.h.dir/build.make CMakeFiles/wordList.h.dir/wordList.c.o
.PHONY : wordList.c.o

wordList.i: wordList.c.i

.PHONY : wordList.i

# target to preprocess a source file
wordList.c.i:
	$(MAKE) -f CMakeFiles/WordList.dir/build.make CMakeFiles/WordList.dir/wordList.c.i
	$(MAKE) -f CMakeFiles/wordList.h.dir/build.make CMakeFiles/wordList.h.dir/wordList.c.i
.PHONY : wordList.c.i

wordList.s: wordList.c.s

.PHONY : wordList.s

# target to generate assembly for a file
wordList.c.s:
	$(MAKE) -f CMakeFiles/WordList.dir/build.make CMakeFiles/WordList.dir/wordList.c.s
	$(MAKE) -f CMakeFiles/wordList.h.dir/build.make CMakeFiles/wordList.h.dir/wordList.c.s
.PHONY : wordList.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... WordList"
	@echo "... wordList.h"
	@echo "... nicholas_wynne_hw4_main.o"
	@echo "... nicholas_wynne_hw4_main.i"
	@echo "... nicholas_wynne_hw4_main.s"
	@echo "... wordList.o"
	@echo "... wordList.i"
	@echo "... wordList.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

